---
language: ruby
before_install:
  - rm Gemfile.lock || true
  - wget https://dl.bintray.com/mitchellh/packer/packer_0.8.2_linux_amd64.zip
  - unzip packer_0.8.2_linux_amd64.zip -d bin
  - PATH=$(pwd)/bin:$PATH
env:
  - PUPPET_VERSION="~> 3.8.1"
  - PUPPET_VERSION="~> 4.0.0"
  - PUPPET_VERSION="~> 4.1.0"
  - PUPPET_VERSION="~> 4.2.1"
